### PR TITLE
Structure

### PR DESCRIPTION
**Pull request by nskartoredjo**
as a developer, I want to have a structure between my files and folders, so that I could find my files within the large database of files.

### CODE REVIEW

**Comment by jannelie** [comment]
ziet er goed uit. Goedgekeurd door mij.

**Comment by ardwennem2** [comment]
Heti is goed

**Comment by HarmenKroon** [comment]
Correcte namen. Prima

**Comment by nskartoredjo** [comment]
+1

**Comment by nskartoredjo** [comment]
De branch blijft 2 dagen levend, dan wordt die verwijderd.

**Pull request merged**
