### PR TITLE
Goalsbuyland

### PR DESCRIPTION
**Pull request by ardwennem2**
As a bot
I want to know when to buy new land.
So that I know if I should buy new land.

### CODE REVIEW

**Comment by jannelie** [comment]
I approve, looks great!

**Comment by HarmenKroon** [comment]
The condition for adopting the goal to buy land is always met after all buildings are demolished. Is this right? Can this only be changed whenever the environment has been updated?

**Comment by jannelie** [comment]
The order is something we need to change when implementing the functionality in the environment

**Comment by HarmenKroon** [comment]
Ok, I approve

**Pull request merged**
