### PR TITLE
Beliefzonelink

### PR DESCRIPTION
**Pull request by ardwennem2**
As a bot
I want to belief in ZoneLinks
so that I can use them

### CODE REVIEW

**Comment by jannelie** [comment]
what was the problem with travis?

**Comment by ardwennem2** [comment]
I aprove as well

**Comment by HarmenKroon** [comment]
Which version of the environment is this?
Can the event module be sorted alphabetically?
Why is service.mod2g edited?
Why are not all tests run?

**Comment by ardwennem2** [comment]
Much better, I apporve

**Comment by nskartoredjo** [comment]
Answers to @HarmenKroon:

1. An old environment that supported [https://github.com/eishub/tygron/pull/61](pull request 61). This should be updated in the development to the new context environment.
2. It will be done
3. It has been reverted, only buy land has been removed (a feature that won't be suported yet)
4. travis.yml should be ignored

**Comment by HarmenKroon** [comment]
I approve

**Pull request merged**
