### PR TITLE
Update final report

### PR DESCRIPTION
**Pull request by ardwennem2**
As a user I want to make the final report so that I can show what I have done.

### CODE REVIEW

**Comment by jannelie** [comment]
Approved, Looks great!

**Comment by HarmenKroon** [comment]
Are `docs/final report/final_report-blx.bib` and `docs/final report/final report.run.xml` both necessary?

**Comment by ardwennem2** [comment]
I fixed your stuff

**Comment by nskartoredjo** [comment]
approved

**Comment by HarmenKroon** [comment]
Approved! Great work CTD :)

**Pull request merged**
