### PR TITLE
Development

### PR DESCRIPTION
**Pull request by jannelie**
As a developer I want to add all finished code to the master so that the master is up to date with only working software.

### CODE REVIEW

**Comment by nskartoredjo** [comment]
ik accepteer deze trekverzoek

**Comment by HarmenKroon** [comment]
我同意

**Comment by ardwennem2** [comment]
それわよい

**Comment by jannelie** [comment]
Please only comment in dutch or english

**Comment by HarmenKroon** [comment]
I approve

**Comment by ardwennem2** [comment]
へといすごおづ

**Pull request merged**
