### PR TITLE
Archupdate

### PR DESCRIPTION
**Pull request by ardwennem2**
As a developer I want to keep the architectual design document updated, So that I can show how our code is designed.

### CODE REVIEW

**Comment by jannelie** [comment]
you should remove the name of Jasper. He is not part of this context anymore.

**Comment by nskartoredjo** [comment]
Tis is a continuation of #50

**Comment by jannelie** [comment]
I approve if the build passes

**Comment by nskartoredjo** [comment]
I approve

**Comment by HarmenKroon** [comment]
I approve

**Pull request merged**
