### PR TITLE
Goalsdemolish

### PR DESCRIPTION
**Pull request by ardwennem2**
the goal will be automaticly made if "Voorzieningen"own buildings that are of none of the categories we need

### CODE REVIEW

**Comment by jannelie** [comment]
looks great. testing can be done in the develop branch. I approve

**Comment by nskartoredjo** [comment]
verwijder `>>>>>>> refs/remotes/origin/development`

**Comment by ardwennem2** [comment]
aangepast

**Comment by nskartoredjo** [comment]
remove 

```
forall percept(stakeholders(CombinedList)), bel(member(StakeholderList, CombinedList), member(stakeholder(StakeholderId, Name, Income, StartBudget), StakeholderList)) do insert(stakeholder(StakeholderId, Name, Income, StartBudget)).

forall percept(stakeholders(CombinedList)), bel(member(IndicatorList, CombinedList), member(indicatorLink(StakeholderId, IndicatorWeights), IndicatorList)) do insert(indicatorLink(StakeholderId, IndicatorWeights)).
```

form the init module

**Comment by nskartoredjo** [comment]
add comments

**Comment by jannelie** [comment]
it is [ci skip] in order to skip the travis build ;)

**Comment by nskartoredjo** [comment]
I approve

**Pull request merged**
