### PR TITLE
Sprint documents week 5

### PR DESCRIPTION
**Pull request by jannelie**
As a developer I want to write a sprint retrospective for this sprint so that I know what we can do better for the next sprint.

As a developer I want to write a sprint backlog for the next sprint so that I will have an overview of the tasks of next week

I also updated the README. Please review

### CODE REVIEW

**Comment by ardwennem2** [comment]
Approve

**Comment by HarmenKroon** [comment]
Retrospective and backlog looks good.
Maybe strikethrough Jasper instead of remove

**Comment by jannelie** [comment]
I striked trhoudh Jasper his name.

**Comment by HarmenKroon** [comment]
I approve

**Pull request merged**
