### PR TITLE
The bot is able to send permits

### PR DESCRIPTION
**Pull request by jannelie**
As a developer I want the agent to ask for a building permit from the Municipality. This allows me to actually build conform measures set by the Municipality

Testing is done manually. See Test document

### CODE REVIEW

**Comment by ardwennem2** [comment]
Ziet er ook goed uit

**Comment by HarmenKroon** [comment]
De main module kan wel nog een description gebruiken.
Ook is de municipality.mas2g niet echt nodig in develop. Dat was meer om te testen

**Comment by jannelie** [comment]
I added comments and removed unused environments and modules.

**Comment by nskartoredjo** [comment]
dont forget to change the state numbers

**Comment by jannelie** [comment]
the state numbers are now correctly both for the main module and the permit module

**Comment by nskartoredjo** [comment]
@jannelie I meant everywhere (you have added more states in TygronEvents.mod2g)

Also, could you ad -d to the travis.yml before the -v (this will add more debug prints)

**Comment by nskartoredjo** [comment]
Looks good for me

Approved

**Comment by ardwennem2** [comment]
Approved

**Pull request merged**
