### PR TITLE
Adds service specific indicator excel files

### PR DESCRIPTION
**Pull request by HarmenKroon**
As a virtual human I want to be able to have knowledge of specific topics in the game.
These indicators allow me to retrieve percepts through the environment.

### CODE REVIEW

**Comment by ardwennem2** [comment]
its fine

**Comment by nskartoredjo** [comment]
change directory

**Comment by nskartoredjo** [comment]
I approve

**Comment by jannelie** [comment]
I approve if the files are in the docs directory

**Pull request closed without merging**
