### PR TITLE
updated arch design

### PR DESCRIPTION
**Pull request by ardwennem2**
As a developer I want to keep the architectual design document updated, So that I can show how our code is designed.

### CODE REVIEW

**Comment by jannelie** [comment]
Did you use the example document on blackboard? I think there should be more information about the architecture.

**Comment by ardwennem2** [comment]
yes, i did use those, what do you mean with the architecture?

**Comment by HarmenKroon** [comment]
I think this update is good
Approve

**Comment by nskartoredjo** [comment]
I approve (after I changed the things I wanted to change)

**Pull request merged**
