### PR TITLE
GoalsBuild

### PR DESCRIPTION
**Pull request by ardwennem2**
should be finished

### CODE REVIEW

**Comment by jannelie** [comment]
why are the interactive design documents added?

**Comment by ardwennem2** [comment]
Because I accidently pulled from master instead of development before, however this should not be an issue for merging.

**Comment by jannelie** [comment]
Okay, I approve.

**Comment by nskartoredjo** [comment]
remove uncommented code.
(testing could be done in the development when the indicators will work)

**Comment by jannelie** [comment]
there is no commented code, this is an explanation I guess.

**Comment by jannelie** [comment]
buildsportcenter is added again, this causes the build to fail, because this is not wroking properly
fix this!

**Comment by nskartoredjo** [comment]
I approve.

**Comment by jannelie** [comment]
okay, I approve again, everything is fixed

**Pull request merged**
